elasticsearch:
  enabled: true
  image: elasticsearch
  imageTag: 7.17.3
  ImagePullPolicy: Never
  replicas: 1
  minimumMasterNodes: 1
  antiAffinity: "soft"
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  esJavaOpts: "-Xmx128m -Xms128m"
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"

  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "standard"
    resources:
      requests:
        storage: 100M

neo4j-community:
  enabled: true
  image: neo4j
  imageTag: 4.2.4-community
  ImagePullPolicy: Never
  acceptLicenseAgreement: "yes"
  defaultDatabase: "graph.db"
  existingPasswordSecret: neo4j-secrets

mysql:
  enabled: true
  image:
    repository: bitnami/mysql
    tag: 8.0.29-debian-10-r23
    PullPolicy: Never
  auth:
    existingSecret: mysql-secrets

cp-helm-charts:
  cp-schema-registry:
    enabled: true
    image: confluentinc/cp-schema-registry
    imageTag: 6.0.10
    ImagePullPolicy: Never
    kafka:
      bootstrapServers: "prerequisites-kafka:9092"
  cp-kafka:
    enabled: false
  cp-zookeeper:
    enabled: false
  cp-kafka-rest:
    enabled: false
  cp-kafka-connect:
    enabled: false
  cp-ksql-server:
    enabled: false
  cp-control-center:
    enabled: false

kafka:
  enabled: true
  image:
    repository: bitnami/kafka
    tag: 3.2.0-debian-10-r4
    ImagePullPolicy: Never

  zookeper:
    enabled: true
    image:
      repository: bitnami/zookeeper
      tag: 3.8.0-debian-10-r64
      ImagePullPolicy: Never
