apiVersion: v2
name: datahub-prerequisites
description: A Helm chart for packages that Datahub depends on
type: application
version: 1.0.0
dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled

  - name: neo4j-community
    version: 1.2.5
    repository: https://equinor.github.io/helm-charts/charts/
    condition: neo4j-community.enabled

  - name: mysql
    version: 9.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled

  - name: cp-helm-charts
    version: 0.6.0
    repository: https://confluentinc.github.io/cp-helm-charts/
    condition: cp-helm-charts.enabled

  - name: kafka
    version: 17.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled

maintainers:
  - name: DataMigrationTeam
